---
version: '2.1'

services:
  ethos-repl-docmosis-service:
    image: "hmcts/ethos-repl-docmosis-service:latest"
    container_name: ethos-repl-docmosis-service
    mem_limit: 500M
    mem_reservation: 400M
    ports:
      - 8081:8081
    depends_on:
      - tornado
    environment:
      TORNADO_URL: "http://tornado:8082/rs/render"
      TORNADO_ACCESS_KEY: ""
      IDAM_API_URL: "http://idam-api:8080"
      CCD_DATA_STORE_API_URL: "http://ccd-data-store-api:4452"
      DOCUMENT_MANAGEMENT_URL: "http://dm-store:8080"
      DOCUMENT_MANAGEMENT_CASEWORKERROLE: "caseworker-ethos"
      SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"
      CCD_GATEWAY_BASE_URL: "http://127.0.0.1:3453"
      APPINSIGHTS_INSTRUMENTATIONKEY: "key"
      ETHOS_S2S_SECRET: "AAAAAAAAAAAAAAAC"
      MICRO_SERVICE: "ccd_gw"

  tornado:
    image: "hmcts/tornado:latest"
    mem_limit: 300M
    mem_reservation: 200M
    ports:
      - 8082:8082
    environment:
      DOCMOSIS_KEY: "FNAD-KLTH-JAMO-DKIA-JAEE-7ILH-YKFQ-FR42-A8FA-A-268E"
      DOCMOSIS_SITE: "Licensed To: Ministry Of Justice.  For use with single project: Reform Document Generation"
      DOCMOSIS_TEMPLATESDIR: "/tmp/templates"

  ccd-user-profile-api:
    image: "hmcts/ccd-user-profile-api:${CCD_USER_PROFILE_API_TAG:-latest}"
    mem_limit: 500M
    mem_reservation: 400M
    environment:
      USER_PROFILE_DB_HOST: ccd-shared-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "${DB_USE_SSL}"
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,ccd_admin
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ccd-shared-database
    links:
      - ccd-shared-database
      - service-auth-provider-api

  ccd-definition-store-api:
    image: "hmcts/ccd-definition-store-api:${CCD_DEFINITION_STORE_API_TAG:-latest}"
    mem_limit: 500M
    mem_reservation: 400M
    environment:
      DEFINITION_STORE_DB_HOST: ccd-shared-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOST: "ccd-elasticsearch"
      ELASTIC_SEARCH_FAIL_ON_IMPORT: "true"
    ports:
      - 4451:4451
    depends_on:
      - ccd-shared-database
      - ccd-user-profile-api
    links:
      - ccd-shared-database
      - ccd-user-profile-api
      - idam-api
      - service-auth-provider-api

  ccd-data-store-api:
    image: "hmcts/ccd-data-store-api:${CCD_DATA_STORE_API_TAG:-latest}"
    mem_limit: 500M
    mem_reservation: 400M
    environment:
      DATA_STORE_DB_HOST: ccd-shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,fpl_case_service,ccd_data,ccd_ps
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOSTS: ccd-elasticsearch:9200
      ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://ccd-elasticsearch:9200"
    ports:
      - 4452:4452
    depends_on:
      - ccd-shared-database
      - ccd-user-profile-api
      - ccd-definition-store-api
    links:
      - ccd-shared-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - idam-api
      - service-auth-provider-api

  idam-api:
    image: hmcts.azurecr.io/hmcts/tidam-api:latest
    mem_limit: 1G
    mem_reservation: 800M
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      IDAM_SUPERUSER_EMAIL: ccd@hmcts.net
      SPRING_DATASOURCE_URL: jdbc:postgresql://ccd-shared-database:5432/idam
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_MAIL_HOST: smtp-server
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      NOTIFY_API_KEY: AAAAAAAAAAAAAAAA
      NOTIFY_CMC_ACTIVATE_USER_TEMPLATE: 76aa8695-64e8-4afd-ae13-bc8385302b1f
      IDAM_SECRET: idam_test_secret
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_ADMIN: "${OAUTH2_CLIENT_CCD_ADMIN}"
      IDAM_CCD_WHITELIST: http://localhost:3451/oauth2redirect
      IDAM_CCD_ADMIN_WHITELIST: https://localhost:3100/oauth2redirect
      NOTIFY: "false"
      NOTIFY_CMC_WELCOME_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE: fake
      NOTIFY_SSCS_WELCOME_USER_TEMPLATE: fake
      NOTIFY_RESET_PASSWORD_TEMPLATE: fake
      NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_CCD_ACTIVATE_USER_TEMPLATE: fake
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
      http_proxy:
      https_proxy:
      no_proxy:
    ports:
      - 4501:8080
    links:
      - smtp-server
      - ccd-shared-database
    depends_on:
      - ccd-shared-database
      - smtp-server

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    mem_limit: 400M
    mem_reservation: 300M
    container_name: service-auth-provider-api
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICEKEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICEKEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICEKEYS_CCD_ADMIN: "${IDAM_KEY_CCD_ADMIN}"
      MICROSERVICEKEYS_FPL_CASE_SERVICE: "${IDAM_KEY_FPL_CASE_SERVICE}"
      TESTING_SUPPORT_ENABLED: "true"

  smtp-server:
    image: mailhog/mailhog
    mem_limit: 10M
    mem_reservation: 5M

  ccd-shared-database:
    build: ../database
    mem_limit: 50M
    mem_reservation: 40M
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DB_USERNAME:
      DB_PASSWORD:
    ports:
      - 5000:5432
    volumes:
      - ccd-docker-ccd-shared-database-data:/var/lib/postgresql/data

  dm-store:
    image: "hmcts/dm-store:${DM_STORE_TAG:-latest}"
    mem_limit: 1G
    mem_reservation: 800M
    command: --wait-for-database 30
    healthcheck:
      disable: true
    environment:
      SERVER_PORT: 8080
      IDAM_SUPERUSER_EMAIL:
      IDAM_SECRET_KEY: "${IDAM_KEY_DM_STORE}"
      GOV_NOTIFY_API_KEY:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ccd-shared-database:5432/evidence
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      #ENABLE_AZURE_STORAGE_CONTAINER: "false"
      #ENABLE_POSTGRES_BLOB_STORAGE: "true"
      STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: "${STORAGEACCOUNT_PRIMARY_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-storage-emulator-azurite:10000/devstoreaccount1}"
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME: "${STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:-hmctstestcontainer}"
      BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED: "${BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY_REQUIRED:-false}"
      BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY: "${BLOBSTORE_MIGRATE_CCD_PUBLIC_KEY:-ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDiQ//gc/G53d9dLCtf123fIYo49gUySuJuxOcw2GtieWTMSy+O7RNtsAIjVf3mCOdDNuN69tZNPEWMdaW8n11s9MwYFahtxDecyn0KIP9MvPsfSMSbxhp/f7kfbdB/H/S5eYea66JTyeJS6uNd76RdHttx0mLO30ZkRcXB25c2SIXhRYsdoeKS5GXHDdNejkQM0S/Ev94x2UunApmYHjWN1XcDhsEsAeF4WHnvYh2XiMn9vHY44AqvbWLlAmCgzaXpz8Xhl0fO7jDKSeReDyuM3UTMaiFFaxuvliGol7aIXq/aVe/miiD2SLxHZ6RxAPW80bhXrzJMTLTCqhCEhzfv someone@somewhere.sometime}"
      SPRING_PROFILES_ACTIVE: dev
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      LOGGING_LEVEL_UK_GOV_HMCTS_IDAM: DEBUG
      IDAM_USER_BASE_URI: http://idam-api:8080
      IDAM_S2S_BASE_URI: http://service-auth-provider-api:8080
      S2S_NAMES_WHITELIST: sscs,divorce,ccd,em_gw,document-management-store,ccd_gw,idam-api,fpl_case_service
      http_proxy:
      https_proxy:
      no_proxy:
      #      logging env vars
      ROOT_APPENDER: JSON_CONSOLE
      JSON_CONSOLE_PRETTY_PRINT: "false"
      REFORM_SERVICE_TYPE: java
      REFORM_SERVICE_NAME: document-management-store
      REFORM_TEAM: cc
      REFORM_ENVIRONMENT: docker
      #      healthcheck env vars
      PACKAGES_ENVIRONMENT: docker
      PACKAGES_PROJECT: evidence
      PACKAGES_NAME: document-management-store
      PACKAGES_VERSION: unknown
    #      debug mode
    #    JAVA_OPTS: -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    links:
      - ccd-shared-database
      - idam-api
      - service-auth-provider-api
    depends_on:
      - ccd-shared-database
      - idam-api
      - service-auth-provider-api
      - azure-storage-emulator-azurite
    ports:
      - 4506:8080
    #   debug port exposed
    #   - 5006:5005

  azure-storage-emulator-azurite:
    image: arafato/azurite
    mem_limit: 50M
    mem_reservation: 30M
    ports:
      - 10000:10000
    environment:
      executable: "blob"
    volumes:
      - ccd-docker-azure-blob-data:/opt/azurite/folder

  ccd-case-management-web:
    image: "hmcts/ccd-case-management-web:${CCD_CASE_MANAGEMENT_WEB_TAG:-latest}"
    mem_limit: 500M
    mem_reservation: 100M
    container_name: ccd-case-management-web
    environment:
      IDAM_LOGIN_URL: https://localhost:3501/login
      CCD_GATEWAY_BASE_URL: http://localhost:3453
      CCD_ACTIVITY_BASE_URL:
      DM_GATEWAY_BASE_URL: https://api-gateway.dev.dm.reform.hmcts.net
      OAUTH2_CLIENT_ID: ccd_gateway
    ports:
      - 3451:3451
    depends_on:
      - ccd-api-gateway

  ccd-api-gateway:
    image: "hmcts/ccd-api-gateway:${CCD_API_GATEWAY_TAG:-latest}"
    mem_limit: 100M
    mem_reservation: 80M
    container_name: ccd-api-gateway
    environment:
      IDAM_BASE_URL: http://idam-api:8080
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_OAUTH2_LOGOUT_ENDPOINT: http://idam-api:8080/session/:token
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_OAUTH2_TOKEN_ENDPOINT: http://idam-api:8080/oauth2/token
      ADDRESS_LOOKUP_TOKEN:
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api

  authentication-web:
    image: hmcts.azurecr.io/hmcts/tidam-authentication-web:latest
    mem_limit: 50M
    mem_reservation: 40M
    environment:
      IDAM_API_URL: http://idam-api:8080
      IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS: "false"
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
    ports:
      - 3501:8000
    links:
      - idam-api
    depends_on:
      - idam-api

volumes:
  ccd-docker-ccd-shared-database-data:
  ccd-docker-azure-blob-data: