spring.datasource.url=jdbc:postgresql://localhost:${ETHOS_REPL_DB_PORT:5050}/${ETHOS_REPL_DB_NAME:ethos}${ETHOS_REPL_DB_CONN_OPTIONS:}
server.port=8082

document_management.url=http://localhost:4506

idam.api.url=http://localhost:5000
idam.api.url.jwkUrl=http://localhost:5000/o/jwks
idam.api.url.oidc=http://localhost:5000/o/token
idam.s2s-auth.url=http://localhost:4502
idam.s2s-auth.microservice=ethos_repl_docmosis_service
idam.client.id=ecm_consumer
idam.client.redirect_uri=http://localhost:8082/oauth2redirect

caseWorkerUserName=admin@hmcts.net
caseWorkerPassword=Pa55word11

ccd.data.store.api.url=http://localhost:4452

tornado.url=http://localhost:9095/api/render
case_document_am.url =http://localhost:4455
feature.secure-doc-store.enabled = false
