apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  RECIPE_BACKEND_URL: "http://ethos-repl-docmosis-service-aat.service.core-compute-aat.internal"