apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  REPL_DOCMOSIS_BACKEND_URL: "http://ethos-repl-docmosis-service-aat.service.core-compute-aat.internal"
  ENVIRONMENT_NAME : "aat"
  TORNADO_URL : "http://tornado:8082/rs/render"
  TORNADO_ACCESS_KEY : ""
  IDAM_API_URL: "http://idam-api:8080"
  DOCUMENT_MANAGEMENT_URL: "http://dm-store:8080"
  SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"