---
version: '3.3'

services:
  ethos-repl-docmosis-service:
    image: "hmcts/ethos-repl-docmosis-service:latest"
    container_name: ethos-repl-docmosis-service
    ports:
      - 8081:8081
    environment:
      TORNADO_URL: "http://tornado:8082/rs/render"
      TORNADO_ACCESS_KEY: ""
      IDAM_API_URL: "http://idam-api:8080"
      DOCUMENT_MANAGEMENT_URL: "http://dm-store:8080"
      DOCUMENT_MANAGEMENT_CASEWORKERROLE: "caseworker-ethos"
      SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"
      APPINSIGHTS_INSTRUMENTATIONKEY: "key"

  tornado:
    image: "hmcts/tornado:latest"
    ports:
      - 8082:8082
    environment:
      DOCMOSIS_KEY: "0OAD-KLTH-JALO-MLIA-DBBH-1ELH-XBKQ-GS91-23ED-8-2358"
      DOCMOSIS_SITE: "Free Trial License"
