---
version: '3.3'

services:
  ethos-repl-docmosis-service:
    image: "hmcts/ethos-repl-docmosis-service:latest"
    container_name: ethos-repl-docmosis-service
    ports:
      - 8081:8081
    environment:
      TORNADO_URL: "http://tornado:8082/rs/render"
      TORNADO_ACCESS_KEY: ""
      IDAM_API_URL: "http://idam-api:8080"
      CCD_DATA_STORE_API_URL: "http://ccd-data-store-api:4452"
      DOCUMENT_MANAGEMENT_URL: "http://dm-store:8080"
      DOCUMENT_MANAGEMENT_CASEWORKERROLE: "caseworker-ethos"
      SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"
      CCD_GATEWAY_BASE_URL: "http://127.0.0.1:3453"
      APPINSIGHTS_INSTRUMENTATIONKEY: "key"
      ETHOS_REPL_SERVICE_S2S_SECRET: "AAAAAAAAAAAAAAAC"
      MICRO_SERVICE: "ethos_repl_service"

  tornado:
    image: "hmcts/tornado:latest"
    ports:
      - 8082:8082
    environment:
      DOCMOSIS_KEY: "FNAD-KLTH-JAMO-DKIA-JAEE-7ILH-YKFQ-FR42-A8FA-A-268E"
      DOCMOSIS_SITE: "Licensed To: Ministry Of Justice.  For use with single project: Reform Document Generation"
