---
version: '3.3'

services:
  ethos-repl-docmosis-service:
    image: "hmcts/ethos-repl-docmosis-service:latest"
    container_name: ethos-repl-docmosis-service
    ports:
      - 8081:8081
    environment:
      TORNADO_URL: "http://tornado:8090/rs/render"
      TORNADO_ACCESS_KEY: ""
      IDAM_API_URL: "http://sidam-api:5000"
      CCD_DATA_STORE_API_URL: "http://ccd-data-store-api:4452"
      DOCUMENT_MANAGEMENT_URL: "http://dm-store:8080"
      DOCUMENT_MANAGEMENT_CASEWORKERROLE: "caseworker-ethos"
      SERVICE_AUTH_PROVIDER_URL: "http://service-auth-provider-api:8080"
      CCD_GATEWAY_BASE_URL: "http://127.0.0.1:3453"
      APPINSIGHTS_INSTRUMENTATIONKEY: "key"
      ETHOS_REPL_SERVICE_S2S_SECRET: "AAAAAAAAAAAAAAAC"
      MICRO_SERVICE: "ethos_repl_service"
      ETHOS_REPL_DB_HOST: "ethos-database"
      ETHOS_REPL_DB_PASSWORD: "ethos"

  tornado:
    image: "hmcts/tornado:latest"
    ports:
      - 8090:8090
    environment:
      DOCMOSIS_KEY: "FNAD-KLTH-JAMO-DKIA-JAEE-7ILH-YKFQ-FR42-A8FA-A-268E"
      DOCMOSIS_SITE: "Licensed To: Ministry Of Justice.  For use with single project: Reform Document Generation"

  ethos-repl-database:
#    build:
#      context: docker/database
    image: "hmcts/ethos-repl-database:latest"
    ports:
      - 5429:5432
    environment:
      ETHOS_REPL_DB_PASSWORD: "ethos"
    volumes:
      - ethos-repl-database-data:/var/lib/postgresql/data

volumes:
  ethos-repl-database-data: