---
version: '3.3'

services:
  ethos-repl-docmosis-service:
    image: "hmcts/ethos-repl-docmosis-service:latest"
    container_name: ethos-repl-docmosis-service
    ports:
      - 8081:8081
    environment:
      TORNADO_URL: "http://tornado:8080/rs/render"
      TORNADO_ACCESS_KEY: ""

  tornado:
    image: "hmcts/tornado:latest"
    ports:
      - 8080:8080
    environment:
      DOCMOSIS_KEY: "0OAD-KLTH-JALO-MLIA-DBBH-1ELH-XBKQ-GS91-23ED-8-2358"
      DOCMOSIS_SITE: "Free Trial License"
