api_gateway_test_certificate_thumbprint = "BC35F646A3F22EFB2CDCF5872FE5F6D596D2EFD4"
tornado_url = "http://tornado:8082/rs/render"
tornado_access_key = ""
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
dm_url = "http://dm-store-aat.service.core-compute-aat.internal"
s2s_url = "http://rpe-service-auth-provider-aat.service.aat.internal"