api_gateway_test_certificate_thumbprint = "BC35F646A3F22EFB2CDCF5872FE5F6D596D2EFD4"
tornado_url = "http://tornado:8082/rs/render"
tornado_access_key = ""
idam_api_url = "https://idam-api.aat.platform.hmcts.net"
dm_url = "http://dm-store-aat.service.aat.platform.hmcts.net"
s2s_url = "http://rpe-service-auth-provider-aat"