api_gateway_test_certificate_thumbprint = "162CD82F0363F36E81218AD218C3C19F862CD479"
tornado_url = "https://docmosis-development.platform.hmcts.net/rs/render"
tornado_access_key = "ZDYxMTkzZTQtMGY2Mi00NDM1LWIyN2ItNGRkNzdjOTczMjAwOjQ1NTE0ODQ"
idam_api_url = "https://idam-api.demo.platform.hmcts.net"
dm_url = "http://dm-store-aat.service.core-compute-demo.internal"
s2s_url = "http://rpe-service-auth-provider-demo.service.core-compute-demo.internal"