capacity = "2"
tornado_url = "https://docmosis-testing.platform.hmcts.net/rs/render"
idam_api_url = "https://idam-api.perftest.platform.hmcts.net"
ccd_data_store_api_url = "http://ccd-data-store-api-perftest.service.core-compute-perftest.internal"
dm_url = "http://dm-store-perftest.service.core-compute-perftest.internal"
s2s_url = "http://rpe-service-auth-provider-perftest.service.core-compute-perftest.internal"
ccd_gateway_url = "https://gateway-ccd.perftest.platform.hmcts.net"
micro_service = "ethos_repl_service"