capacity = "2"
api_gateway_test_certificate_thumbprint = "8A13CF9CC991EDE7A2A227E4153A54F6E3157774"
tornado_url = "https://docmosis-development.platform.hmcts.net/rs/render"
tornado_access_key = "ZDYxMTkzZTQtMGY2Mi00NDM1LWIyN2ItNGRkNzdjOTczMjAwOjQ1NTE0ODQ"
idam_api_url = "https://idam-api-idam-sprod.service.core-compute-idam-sprod.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-sprod.service.core-compute-sprod.internal"
dm_url = "http://dm-store-sprod.service.core-compute-sprod.internal"
s2s_url = "https://rpe-service-auth-provider-sprod.service.core-compute-sprod.internal"
