tornado_url = "https://docmosis-development.platform.hmcts.net/rs/render"
tornado_access_key = "ZDYxMTkzZTQtMGY2Mi00NDM1LWIyN2ItNGRkNzdjOTczMjAwOjQ1NTE0ODQ"
idam_api_url = "https://idam-api-idam-saat.service.core-compute-idam-saat.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-saat.service.core-compute-saat.internal"
dm_url = "http://dm-store-saat.service.core-compute-saat.internal"
s2s_url = "https://rpe-service-auth-provider-saat.service.core-compute-saat.internal"
ccd_gateway_url = "https://gateway-ccd.saat.platform.hmcts.net"