api_gateway_test_certificate_thumbprint = "96FFD94D9484C992FDFBA870AD5631F8667B40EC"
tornado_url = "http://tornado:8082/rs/render"
tornado_access_key = ""
idam_api_url = "http://idam-api-idam-saat.service.core-compute-idam-saat.internal"
dm_url = "http://dm-store-saat.service.core-compute-saat.internal"
s2s_url = "http://rpe-service-auth-provider-saat.service.saat.internal"