api_gateway_test_certificate_thumbprint = "4A98AB1CFFBA46CACBC7D8D3E10FDA667261DFAA"
tornado_url = "https://docmosis-development.platform.hmcts.net/rs/render"
tornado_access_key = "ZDYxMTkzZTQtMGY2Mi00NDM1LWIyN2ItNGRkNzdjOTczMjAwOjQ1NTE0ODQ"
idam_api_url = "https://idam-api-idam-sandbox.service.core-compute-idam-sandbox.internal"
dm_url = "http://dm-store-aat.service.core-compute-demo.internal"
s2s_url = "http://rpe-service-auth-provider-demo"
