api_gateway_test_certificate_thumbprint = "7A252365843BCFD293BF36EE1A56870721B306FC"
tornado_url = "http://tornado:8082/rs/render"
tornado_access_key = ""
idam_api_url = "https://idam-api-idam-sprod.service.core-compute-idam-sprod.internal"
dm_url = "http://dm-store-sprod.service.sprod.platform.hmcts.net"
s2s_url = "https://rpe-service-auth-provider-sprod.service.core-compute-sprod.internal"