api_gateway_test_certificate_thumbprint = "7A252365843BCFD293BF36EE1A56870721B306FC"
tornado_url = "http://tornado:8082/rs/render"
tornado_access_key = ""
idam_api_url = "https://preprod-idamapi.reform.hmcts.net:3511"
dm_url = "http://dm-store-sprod.service.core-compute-sprod.internal"
s2s_url = "http://rpe-service-auth-provider-sprod.service.sprod.internal"