tornado_url = "https://docmosis-development.platform.hmcts.net/rs/render"
idam_api_url = "http://idam-api-idam-sprod.service.core-compute-idam-sprod.internal"
ccd_data_store_api_url = "http://ccd-data-store-api-sprod.service.core-compute-sprod.internal"
dm_url = "http://dm-store-sprod.service.core-compute-sprod.internal"
s2s_url = "http://rpe-service-auth-provider-sprod.service.core-compute-sprod.internal"
ccd_gateway_url = "https://gateway-ccd.sprod.platform.hmcts.net"
micro_service = "ethos_repl_service"