name: Sonar Workflow
on:
  pull_request:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'oracle'
      - name: SonarCloud Scan
        run: ./gradlew sonarqube -Dsonar.pullrequest.key=${{ github.event.number }}
          -Dsonar.pullrequest.base=${{ github.event.pull_request.base.sha }}
          -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.sha }}
          -Dsonar.pullrequest.provider=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}